### ISSUE TITLE
Cannot add any webhooks

### ISSUE THREAD

**Issue by keyvanfatehi** [Strider-CD/strider-webhooks#4]
Hi. I am running https://github.com/Strider-CD/strider/commit/756c91f0f3e04ffbc5b71d610ed96ff845385fca but the webhooks section does not let me add any webhooks. Screenshot enclosed. 
![selection_004](https://cloud.githubusercontent.com/assets/175305/3210337/c16f1536-eeb4-11e3-9f86-0b71e82ad102.png)
Thanks!

**Comment by marcuspoehls** [comment]
I got some more insights of this problem on server side and the issue occurs during plugin configuration save. Sending the webhook config from frontend to the server has the following payload

```
[ { 
    '$$hashKey': '01U',
    title: 'test',
    url: 'http://server.url/',
    secret: 'sha1=secret',
    format: '{}' 
} ]
```

Trying to save these information results in a problem running Strider with **MongoDB 2.6 and greater**. The `$` sign is reserved in Mongo for internal functionality.

The Mongo error when trying to save

```
info: { [MongoError: The dollar ($) prefixed field '$$hashKey' in 'branches.0.plugins.2.config.0.$$hashKey' is not valid for storage.]
name: 'MongoError',
code: 52,
err: 'The dollar ($) prefixed field \'$$hashKey\' in \'branches.0.plugins.2.config.0.$$hashKey\' is not valid for storage.' }
```

**My failed try to resolve the problem**
I deleted the `$$hashKey` key from the sent config object and wanted to store the plugin config to Mongo. Looks like the save operation went smooth, at least there wasn’t any error in the console. When reloading the webhook config page in project’s plugin settings page (frontend), no config gets loaded and stored. And also no webhook gets fired during test runs.

@jaredly @knownasilya Did you guys made any progress on this issue in the past?

**Comment by knownasilya** [comment]
Sorry, I've yet to look at the issue. I'm up for helping you out if you want to tackle this. I'll be on IRC today.

**Comment by marcuspoehls** [comment]
I don't have time to work on this issue today. Will do it next if nobody did it then.

**Comment by knownasilya** [comment]
In usually on IRC anyway :smile:

**Comment by marcuspoehls** [comment]
:grin: :+1:

**Comment by marcuspoehls** [comment]
Found the problem and submitted the pull request earlier than expected :smile:
